import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = dirname(__dirname);

const pkg = JSON.parse(readFileSync(new URL('../package.json', import.meta.url), 'utf8'));

const generatedDir = new URL('../src/generated/', import.meta.url);
mkdirSync(generatedDir, { recursive: true });

writeFileSync(
  new URL('./version.ts', generatedDir),
  [
    '// Auto-generated by scripts/prebuild-version.mjs — do not edit',
    `export const BUILD_VERSION = ${JSON.stringify(pkg.version)};`,
    `export const PACKAGE_URL = ${JSON.stringify(pkg.name)};`,
    'export const FEEDBACK_CHANNEL = "https://github.com/ClewCode/ClewCode/issues";',
    'export const ISSUES_EXPLAINER = "visit https://github.com/ClewCode/ClewCode/issues";',
    '',
  ].join('\n'),
  'utf8',
);
